---
abstract: 'Module signature file manipulation'
author:
  - 'Audrey Tang <cpan@audreyt.org>'
build_requires:
  ExtUtils::MakeMaker: 6.36
  IPC::Run: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.36
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.16'
license: unrestricted
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Module-Signature
no_index:
  directory:
    - inc
    - t
requires:
  File::Temp: 0
  IO::Socket::INET: 0
  perl: '5.005'
resources:
  repository: http://github.com/audreyt/module-signature
version: '0.90'
